name: Generate GitHub Stats SVGs

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate Stats Cards
        uses: soulteary/github-readme-stats-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: tasnia25ahmed
          output_dir: ./profile-stats
          stats_theme: radical
          stats_hide_border: true
          stats_show_icons: true
          langs_theme: radical
          langs_hide_border: true
          langs_layout: compact

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./profile-stats/*.svg
          git commit -m "chore: update github profile stats SVGs" || exit 0
          git push
